### PR TITLE
X-Carve Pro Overview page & X-Carve Pro 4x4 and 4x2 product pages

### PR DESCRIPTION
**Pull request by arthurstomp**
### PR Summary: 

This PR implement sections for the implementation of X-Carve PRO overview page as especified on [Figma](https://www.figma.com/file/Dzfu2ajVNiRoYmVS5IGGGd/X-Carve-Pro-Webpages---Delivery?type=design&node-id=1-672&t=57PENUmMhaz6IlMe-0)

- [Store](url)
- [Editor](https://inventablesusa.myshopify.com/admin/themes/130574549049/editor?previewPath=%2Fpages%2Fcontact%3Fview%3Dx-carve-pro-overview&section=template--15875216113721__2dc3f5bf-326f-419e-a360-1b42ec22ace3)
- [Preview](https://l9z912p2z6osn9d0-60429828153.shopifypreview.com/pages/contact?view=x-carve-pro-overview)

screencapture-localhost-9292-pages-contact-2023-05-31-16_29_54

### Why are these changes introduced?

Fixes #0.

### Decision log

| # | Decision | Alternatives | Rationale | Downsides |
|---|---|---|---|---|
| 1 |   |   |   |   |

### Testing steps/scenarios

- [ ] Step 1

### Checklist
- [ ] Added PR summary for [release notes](https://themes.shopify.com/themes/dawn/styles/default#ReleaseNotes)
- [ ] Requested review from UX (Only for changes that are affecting the experience or perceivable visual details)
- [ ] Created a ticket for the [help.shopify.com](https://help.shopify.com) documentation team about updates to theme settings. (Internal-only task)
- [ ] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [ ] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [ ] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [ ] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [ ] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

### CODE REVIEW

**Comment by thomasjlee** [comment]
XCP Overview Page looks great. I see a few issues:

https://github.com/inventables/ecomm-theme-dawn/assets/26750330/c9d5641e-084c-4c8f-a589-8a2fb3377ec3

- At "tablet" width, there is extra margin on the right side
- At "tablet" width, the logo, links, and buttons in the sub-nav look inconsistent
  - Could we make the text smaller or adjust spacing at that breakpoint so the text does not wrap onto a second line?
- At "tablet" width, the multicolumn sections (Design, Cut, Scale) show each image with a lot of empty space
  - Is this a setting we need to change in the Editor, or does it need to be updated in the code?

After we merge this we also need to make changes in the Editor. Making a list here so we don't forget (this may not be exhaustive):
- [ ] Update hrefs for Nav Items within XCPNavbar
- [ ] Update background video URL and Button Link for the XCP Hero
- [ ] Update videos or GIFs of Design, Cut, Scale sections
- [ ] Update the cover image of the Poughkeepsie Woodworks video
- [ ] Link for "Meet Your Next Employee" Button
- [ ] Button Links for "Pick Your Pro" section
- [ ] Easel "Start a Free Trial" Button Link
- [ ] URL for "Pick Your Pro" Button in "Carve Big" section

**Review by thomasjlee — CHANGES_REQUESTED** [review]
A few issues with the responsive design (see my other comment and screen recording). Otherwise, this looks good.

**Comment by arthurstomp** [comment]
@thomasjlee thank you for the review
I've fixed the issues related to "tablet" dimentions.
For the navbar, the solution that worked best was to use the mobile navbar on tablet.

**Review by thomasjlee — CHANGES_REQUESTED** [review]
https://github.com/inventables/ecomm-theme-dawn/assets/26750330/2b50a4b1-d248-4412-8b41-f8450c4cdfca

There is still some horizontal overflow and scrolling at this breakpoint.

**Review by thomasjlee — APPROVED** [review]

**Pull request merged**
