### PR TITLE
XC/XCP Comparison and XCP Financing pages 

### PR DESCRIPTION
**Pull request by arthurstomp**
### PR Summary: 

This PR implements the pages for "XC Vs. XCP" and "XCP Financing".

- "XC Vs. XCP" : [preview](https://cz5t5tnc4i7w84id-60429828153.shopifypreview.com/pages/contact?view=xc-comparison) | [editor](https://inventablesusa.myshopify.com/admin/themes/130607349817/editor?previewPath=%2Fpages%2Fcabinets-use-case%3Fview%3Dxc-comparison)
- "XCP Financing": [preview](https://cz5t5tnc4i7w84id-60429828153.shopifypreview.com/pages/contact?view=xcp-financing) | [editor](https://inventablesusa.myshopify.com/admin/themes/130607349817/editor?previewPath=%2Fpages%2Fcabinets-use-case%3Fview%3Dxcp-financing)

screencapture-cz5t5tnc4i7w84id-60429828153-shopifypreview-pages-contact-2023-06-19-19_41_50

screencapture-cz5t5tnc4i7w84id-60429828153-shopifypreview-pages-contact-2023-06-19-19_42_12

### CODE REVIEW

**Review by natedemery — CHANGES_REQUESTED** [review]
@arthurstomp is there a way to refactor this to make it easier to add or remove rows and columns in the theme editor? For instance, if a non-developer wanted to go in and add a new row to the table.

**Comment by arthurstomp** [comment]
@natedemery i think that is a way.

I'm thinking on having a section that serve just as a placement for the columns among other sections. Columns would then be their own section with the blocks being their lines. 

The new column sections would be hidden at first, but a script function would show them in the correct position in the page, after it finishes loading.

This solution will required the user to remember to add the "placement section" correctly so the columns appear at the end.

**Comment by natedemery** [comment]
@arthurstomp 
>The new column sections would be hidden at first, but a script function would show them in the correct position in the page, after it finishes loading.

would this cause a delay in load time for the page?

**Comment by arthurstomp** [comment]
@natedemery I dont think it will cause any delay. The content will already be rendered. The script just copy and paste the elements into the correct position.

**Comment by gensym** [comment]
Will it cause a cumulative layout shift?

**Comment by arthurstomp** [comment]
@gensym What do you mean by "cumulative layout shift"?
The definition to `display: flex` only happens inside the `columns-position` element. If the columns were to appear outside of `columns-position` they would look like narrow long sections, one on top of the other.

The only caveat of this "position section" solution is that for changes to appear in the editor preview they need to be saved.

I've finished the refactoring. The PR is ready for a new review. Now users should have more ease on adding new column, and new lines, as they wish.

CC: @natedemery 

"XC Vs. XCP" : [preview](https://kkjze4pvnu0l1ajh-60429828153.shopifypreview.com/pages/contact?view=xc-comparison) | [editor](https://inventablesusa.myshopify.com/admin/themes/130607349817/editor?previewPath=%2Fpages%2Fcabinets-use-case%3Fview%3Dxc-comparison)
"XCP Financing": [preview](https://kkjze4pvnu0l1ajh-60429828153.shopifypreview.com/pages/contact?view=xcp-financing) | [editor](https://inventablesusa.myshopify.com/admin/themes/130607349817/editor?previewPath=%2Fpages%2Fcabinets-use-case%3Fview%3Dxcp-financing)

https://github.com/inventables/ecomm-theme-dawn/assets/1282750/47fcaed6-8f37-4aa9-9a46-a5efb8dadc06

**Comment by natedemery** [comment]
@arthurstomp Cumulative layout shift is a measure of how much the page moves as it loads. A high amount of CLS is bad from an SEO perspective. We're trying to keep this in mind as we develop new components and pages for the site. Having said that, I don't think it's a blocker for this to be merged.

**Review by thomasjlee — APPROVED** [review]

**Pull request merged**
